GO_EASY_ON_ME=1
include theos/makefiles/common.mk

TWEAK_NAME = photosplugin
photosplugin_FILES = CameraPlus.xm Safari.xm AppStore.xm
photosplugin_FRAMEWORKS= Twitter UIKit Foundation
photosplugin_PRIVATE_FRAMEWORKS= AppSupport

TARGET_IPHONEOS_DEPLOYMENT_VERSION = 5.0

include $(THEOS_MAKE_PATH)/tweak.mk
